# Generated by Django 4.1.5 on 2023-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='demo_vms',
            field=models.ManyToManyField(related_name='tags', to='tag_api.vm'),
        ),
    ]
