# Generated by Django 4.1.5 on 2023-12-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0002_remove_vm_tags_tagsmodel_demo_vms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsmodel',
            old_name='demo_vms',
            new_name='vms',
        ),
    ]
