# Generated by Django 4.1.5 on 2023-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_api', '0003_rename_demo_vms_tagsmodel_vms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsmodel',
            name='vms',
        ),
        migrations.AddField(
            model_name='vm',
            name='tags',
            field=models.ManyToManyField(related_name='vms', to='tag_api.tagsmodel'),
        ),
    ]
